"""create db

Revision ID: 4c1679bcfdbf
Revises: 
Create Date: 2020-06-04 20:11:32.271218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1679bcfdbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_number', sa.String(), nullable=True),
    sa.Column('notice_id', sa.String(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auctions')
    # ### end Alembic commands ###
